/**:
  ros__parameters:
    lio.map.save_map: true
    lio.map.if_filter: true
    lio.map.save_map_dir: "map"
    lio.map.map_name: "map.pcd"
    lio.map.ds_size: 0.25
    lio.map.save_interval: 100

    lio.ros.lidar_topic: "/rslidar_points"
    lio.ros.imu_topic: "/rslidar_imu_data"

    lio.sensor.lidar_type: 2
    lio.sensor.blind: 0.2
    lio.sensor.maxrange: 60.0
    lio.sensor.filter_rate: 3
    lio.sensor.enable_downsample: true
    lio.sensor.voxel_fliter_size: 0.5
    lio.sensor.gravity_norm: 9.7946
    lio.sensor.imu_type: 1
    lio.sensor.imu_na: 0.1
    lio.sensor.imu_ng: 0.1
    lio.sensor.imu_nba: 0.0001
    lio.sensor.imu_nbg: 0.0001

    lio.extrinsic.lidar_imu: [-0.0, -0.0, 0.0,
                              0.0, -1.0, 0.0,
                              -1.0, 0.0, 0.0,
                              0.0, 0.0, -1.0]
    # lio.extrinsic.lidar_imu: [0.00425, 0.00418, -0.00446,
    #                           -0.0040505, -0.9999892, -0.0022646,
    #                           -0.9999912,  0.0040529, -0.0010374,
    #                           0.0010466,  0.0022604, -0.9999969]
    lio.extrinsic.odom_robo: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

    lio.hash_map.hash_capacity: 2000000
    lio.hash_map.vox_resolution: 0.5

    lio.kf.kf_type: 0
    lio.kf.kf_max_iterations: 4
    lio.kf.kf_align_gravity: true
    lio.kf.kf_quit_eps: 0.001

    lio.output.robot: true
    lio.output.plan_env_world: false
    lio.output.plan_env_body: false
    lio.output.ml_map: false
    lio.output.planner: false
    lio.output.map: true
    lio.output.dense: true
    lio.output.pub_step: 1

    lio.eva.timer: true